# Generated by Django 5.1.7 on 2025-06-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='victorina',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Stata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('victorina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.victorina')),
            ],
        ),
        migrations.AddField(
            model_name='victorina',
            name='users',
            field=models.ManyToManyField(related_name='victorins', through='main_app.Stata', to=settings.AUTH_USER_MODEL),
        ),
    ]
